# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb24786ec3cf9625e7fb56976ded9b6ef3582f1106af70dc4e200b3524790a9b67aa05a7554dcf1c47953710ec77d81ac6ff1ef5e8450ce4d93b548bc35b82ce

test:
  secret_key_base: c2728c6fc10fe292b814883366b550920d353323637eeaba775b3c38577b0db708ff73d7190f2c88df8e712e58272f059ae3d9a6bca001d561a3c5d250133e5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
